# Time to set when the day vote wins, 1000 is 7:00AM
day: 1000
# Time to set when the night vote wins, 14000 is 8:00PM
night: 14000
# This is the $ it will cost to start a vote, if you set it to 0 it will disable this feature
starting_cost: 0
# Vote percent - Players will need this percent of players in the current world(not server!) to vote( 20 = 20%, 100 players in the world would need 20 players to vote for it)
vote_percent: 20



# Message config
starting_vote:
 - "&7[TimeVote] &a[USERNAME] &9has started a time vote!"
 - "&7[TimeVote] &9If you want to vote for [DAYNIGHT] type &a/VoteTime vote &9it needs [VOTES] to pass!"
