# Time to set when the day vote wins, 1000 is 7:00AM
day: 1000

# Time to set when the night vote wins, 14000 is 8:00PM
night: 14000

# This is the $ it will cost to start a vote, if you set it to 0 it will disable this feature
starting_cost: 0

# Vote percent - Players will need this percent of players in the current world(not server!) to vote( 0.20 = 20%, 100 players in the world would need 20 players to vote for it)
# 0.10 = 10%
# 0.50 = 50%
# 0.90 = 90%
vote_percent: 0.20

# Vote length in seconds, 120 = 2 minutes
vote_length: 120.0

# Message config, Optional placeholders: [USERNAME], [DAYNIGHT] [VOTES]
starting_vote:
 - "&6[TimeVote] &a[USERNAME] &9has started a time vote!"
 - "&6[TimeVote] &9If you want to vote for [DAYNIGHT] type &a/VoteTime vote &9it needs [VOTES] vote(s) to pass!"

err_vote_in_progress: "&6[TimeVote] &4There is already a time vote in progress!"

# Optional placeholders:
# [STATUS] = passed or failed
# [VOTES] = how many players voted for it
# [DAYNIGHT] = day or night
vote_ended: "&6[TimeVote] &9TimeVote has &a[STATUS] &9with &a[VOTES] &9votes for &a[DAYNIGHT]&9!"