# Time to set when the day vote wins, 1000 is 7:00AM
day: 1000

# Time to set when the night vote wins, 14000 is 8:00PM
night: 14000

# This is the $ it will cost to start a vote, if you set it to 0 it will disable this feature
starting_cost: 0

# Vote percent - Players will need this percent of players in the current world(not server!) to vote( 0.20 = 20%, 100 players in the world would need 20 players to vote for it)
# 0.10 = 10%
# 0.50 = 50%
# 0.90 = 90%
vote_percent: 0.20

# Vote length in seconds, 120 = 2 minutes
vote_length: 120.0

# Message config, Optional placeholders:
# [USERNAME] = Username who started the vote
# [DAYNIGHT] = Day or Night
# [VOTES] = Required votes to pass
# [TIME] = Seconds till vote ends
# [WORLD] = World that will have changed time
starting_vote:
 - "&6[TimeVote] &a[USERNAME] &9has started a time vote!"
 - "&6[TimeVote] &9If you want to vote for &a[DAYNIGHT] &9in &a[WORLD] &9type &a/TimeVote vote &9it needs &a[VOTES] &9vote(s) to pass!"
 - "&6[TimeVote] &9The vote will end in [TIME] seconds!"

err_vote_in_progress: "&6[TimeVote] &4There is already a time vote in progress!"
err_not_in_progress: "&6[TimeVote] &4There is no vote in progress right now!"

# Optional placeholders:
# [STATUS] = passed or failed
# [VOTES] = how many players voted for it
# [REQVOTES] = how many votes it needed to pass
# [DAYNIGHT] = day or night
vote_ended: "&6[TimeVote] &9TimeVote has &a[STATUS] &9with &a[VOTES]&9/&a[REQVOTES] &9votes for &a[DAYNIGHT]&9!"

you_voted: "&6[TimeVote] &9Thanks for voting!"
you_already_voted: "&6[TimeVote] &4You already voted!"

# [WORLD] = world the vote is taking place in
err_wrong_world: "&6[TimeVote] &4You can't vote from this world, the vote is taking place in &a[WORLD]!"