name: TimeVote
version: 1.4.0
author: bittiez
main: US.bittiez.TimeVote.main
commands:
    timevote:
        description: Various TimeVote commands
        usage: /TimeVote
permissions:
    TimeVote.start:
        description: Allows the use of /TimeVote new|start
    TimeVote.vote:
        description: Allows the use of /TimeVote vote
    TimeVote.reload:
        description: Allows the use of /TimeVote reload
    TimeVote.updates:
        description: Receive update notifications
        default: op